language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
matrix:
  env:
    global:
      - CI_TEST=no-lint
  include:
    - node_js: "5"
      script: npm run lint
      env:
        - CI_TEST=lint-only
